Synchronize Secret Format and Usage (#1620)
This change makes our usage of AWS secrets for basic auth consistent across the solution (minus K8s which will have a separate task for its secret management). It also includes various improvement for the MA CDK library such as removing some invalid context options, making task names readable and predictable, and removing the OS container stack which was causing additional complexity and is not being used. This change also provides a way for RFS and Replayer services to load specified arguments from environment variables, as would be the case when a secret is provided to ECS or EKS as this is how it provides the values to the container

Note: This includes a breaking change to secret format
Previously:
We expected an AWS secret to contain only the password value as plaintext with no structure and would expect the username through a separate plaintext argument

myStrongPassword123!
Now:
We follow the standard AWS secret format of containing both the username and password as Key-Value pairs within the secret

{"username":"admin","password":"myStrongPassword123!"}
The console library will produce errors like below when using an improperly structured secret:

migration-console (~) -> console clusters cat-indices 

WARNING: Cluster information may be stale. Use --refresh to update.

SOURCE CLUSTER
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test_e2e_0001_integ_full_jul9_2 U--CcY4FQVGQx30DY7q7LA   3   0          3            0     13.3kb         13.3kb

TARGET CLUSTER
Error: Unable to perform cat-indices command with message: Expected secret arn:aws:secretsmanager:us-east-1:123456789012:secret:test-jul2-secret-Y8JbPm to be a JSON object with username and password fields
Or a secret with missing keys:

migration-console (~) -> console clusters curl target_cluster /
Error: Unable to perform cluster command with message: Secret arn:aws:secretsmanager:us-east-1:123456789012:secret:test-jul2-secret-Y8JbPm is missing required key(s): username, password
Other Fixes
Task roles in AWS now follow a consistent pattern like below:

OSMigrations-full-es68-3-us-east-1-capture-proxy-task
OSMigrations-full-es68-3-us-east-1-reindex-from-snapshot-task
OSMigrations-full-es68-3-us-east-1-target-cluster-proxy-task
OSMigrations-full-es68-3-us-east-1-traffic-replayer-default-task
OSMigrations-full-es68-3-us-east-1-migration-console-task
Removed printing RFS args twice on every startup
Added basic logic for RFS and Replayer to redact password fields when printing args at startup
Removed printing stack traces for middleware layer for cat-indices and cluster curl commands

---------

Signed-off-by: Tanner Lewis <lewijacn@amazon.com>